"""Win32 PE header segment.

Dumps the relevant fields of the DOS stub, the COFF file header, the
optional header and the section table as ``.byte`` / ``.long`` / ``.ascii``
directives, mirroring the layout produced by the linker so the segment
round-trips byte-for-byte.

The segment's ``rom_end`` is expected to point at (or just past) the end of
the section table — usually the first non-zero byte of the first real
section. Anything inside that range is emitted verbatim so the alignment
padding the linker inserted before the first section is preserved.
"""

import struct
from typing import List

from ..common.header import CommonSegHeader
from ...platforms import win32 as win32_platform


_MACHINE_TYPES = {
    0x014C: "i386",
    0x0162: "MIPS R3000 LE",
    0x0166: "MIPS R4000 LE",
    0x0168: "MIPS R10000",
    0x0184: "Alpha AXP",
    0x01C0: "ARM (legacy CE)",
    0x01C2: "ARM Thumb",
    0x01C4: "ARMNT (Thumb-2)",
    0x01F0: "PowerPC LE",
    0x01F1: "PowerPC w/ FP",
    0x0200: "Itanium (IA-64)",
    0x0266: "MIPS16",
    0x0366: "MIPSFPU",
    0x0466: "MIPSFPU16",
    0x0EBC: "EFI byte code",
    0x5032: "RISC-V 32-bit",
    0x5064: "RISC-V 64-bit",
    0x5128: "RISC-V 128-bit",
    0x6232: "LoongArch 32-bit",
    0x6264: "LoongArch 64-bit",
    0x8664: "amd64",
    0x9041: "Mitsubishi M32R LE",
    0xAA64: "ARM64",
    0xC0EE: "CLR/CEE",
}


_SUBSYSTEMS = {
    0: "UNKNOWN",
    1: "NATIVE",
    2: "WINDOWS_GUI",
    3: "WINDOWS_CUI",
    5: "OS2_CUI",
    7: "POSIX_CUI",
    8: "NATIVE_WINDOWS",
    9: "WINDOWS_CE_GUI",
    10: "EFI_APPLICATION",
    11: "EFI_BOOT_SERVICE_DRIVER",
    12: "EFI_RUNTIME_DRIVER",
    13: "EFI_ROM",
    14: "XBOX",
    16: "WINDOWS_BOOT_APPLICATION",
}

_DLL_CHARACTERISTICS = [
    (0x0020, "HIGH_ENTROPY_VA"),
    (0x0040, "DYNAMIC_BASE"),
    (0x0080, "FORCE_INTEGRITY"),
    (0x0100, "NX_COMPAT"),
    (0x0200, "NO_ISOLATION"),
    (0x0400, "NO_SEH"),
    (0x0800, "NO_BIND"),
    (0x1000, "APPCONTAINER"),
    (0x2000, "WDM_DRIVER"),
    (0x4000, "GUARD_CF"),
    (0x8000, "TERMINAL_SERVER_AWARE"),
]


_FILE_CHARACTERISTICS = [
    (0x0001, "RELOCS_STRIPPED"),
    (0x0002, "EXECUTABLE_IMAGE"),
    (0x0004, "LINE_NUMS_STRIPPED"),
    (0x0008, "LOCAL_SYMS_STRIPPED"),
    (0x0010, "AGGRESSIVE_WS_TRIM"),
    (0x0020, "LARGE_ADDRESS_AWARE"),
    (0x0080, "BYTES_REVERSED_LO"),
    (0x0100, "32BIT_MACHINE"),
    (0x0200, "DEBUG_STRIPPED"),
    (0x0400, "REMOVABLE_RUN_FROM_SWAP"),
    (0x0800, "NET_RUN_FROM_SWAP"),
    (0x1000, "SYSTEM"),
    (0x2000, "DLL"),
    (0x4000, "UP_SYSTEM_ONLY"),
    (0x8000, "BYTES_REVERSED_HI"),
]


def _decode_flags(value: int, table) -> str:
    names = [name for bit, name in table if value & bit]
    # Surface any leftover bits — preserves information when a binary
    # uses a flag combination we haven't tabulated (e.g. newer
    # IMAGE_DLLCHARACTERISTICS values).
    known_mask = 0
    for bit, _ in table:
        known_mask |= bit
    leftover = value & ~known_mask
    if leftover:
        names.append(f"unknown 0x{leftover:X}")
    return " | ".join(names) if names else "(none)"


class Win32SegHeader(CommonSegHeader):
    """The PE header segment.

    Overrides `get_linker_section` to `.header` so the splat-generated
    linker script pulls bytes from the right input section name —
    header.s emits `.section .header` (matching the PE convention)
    rather than the default `.data` that the base class would assume.

    Emits a structured `.s` file covering DOS stub, PE signature,
    COFF file header, optional header (PE32 or PE32+ specific
    layout), every populated data directory, and the section table.
    Each field renders as a width-correct `.short` / `.long` / etc.
    directive with a trailing comment naming the field — the
    generated bytes match the original PE header byte-for-byte. A
    one-page human-readable summary block precedes the byte
    emission, decoding Machine / ImageBase / EntryPoint /
    Subsystem / characteristics flags / sections / exports /
    imports / PDB / TLS / resources by name."""

    def get_linker_section(self) -> str:
        # Override the default `.data` so the linker script's
        # `<file>.o(.header)` reference matches the section name that
        # parse_header() emits via `.section .header`.
        return ".header"

    @staticmethod
    def _le(data: bytes) -> bytes:
        """Reverse little-endian numeric fields so `.long`/`.short` produce
        the same byte sequence as the source file."""
        return data[::-1]

    def parse_header(self, rom_bytes) -> List[str]:
        assert isinstance(self.rom_start, int)
        assert isinstance(self.rom_end, int)
        pe = win32_platform.info

        out: List[str] = []
        out.extend(self._summary_block(pe))
        out.append(".section .header")
        out.append("")

        # DOS header magic + the rest of the MS-DOS stub.
        out.append("/* IMAGE_DOS_HEADER */")
        out.append(self.get_line("ascii", rom_bytes[0x00:0x02], "Magic 'MZ'"))
        # Dump bytes 0x02..0x3C as raw bytes — the layout varies between
        # toolchains and splat just needs to round-trip them.
        out.append(self._byte_block(rom_bytes[0x02:0x3C], "DOS header tail"))
        out.append(self.get_line("long", self._le(rom_bytes[0x3C:0x40]), "e_lfanew"))
        out.append("")

        pe_off = pe.pe_header_offset
        if pe_off > 0x40:
            out.append("/* DOS stub */")
            out.append(self._byte_block(rom_bytes[0x40:pe_off], "DOS stub bytes"))
            out.append("")

        # PE signature + COFF file header.
        out.append("/* PE signature + IMAGE_FILE_HEADER */")
        out.append(self.get_line("ascii", rom_bytes[pe_off : pe_off + 4], "Signature"))
        out.append(
            self.get_line(
                "short", self._le(rom_bytes[pe_off + 4 : pe_off + 6]), "Machine"
            )
        )
        out.append(
            self.get_line(
                "short",
                self._le(rom_bytes[pe_off + 6 : pe_off + 8]),
                "NumberOfSections",
            )
        )
        out.append(
            self.get_line(
                "long",
                self._le(rom_bytes[pe_off + 8 : pe_off + 12]),
                "TimeDateStamp",
            )
        )
        out.append(
            self.get_line(
                "long",
                self._le(rom_bytes[pe_off + 12 : pe_off + 16]),
                "PointerToSymbolTable",
            )
        )
        out.append(
            self.get_line(
                "long",
                self._le(rom_bytes[pe_off + 16 : pe_off + 20]),
                "NumberOfSymbols",
            )
        )
        size_opt_hdr = struct.unpack_from("<H", rom_bytes, pe_off + 20)[0]
        out.append(
            self.get_line(
                "short",
                self._le(rom_bytes[pe_off + 20 : pe_off + 22]),
                "SizeOfOptionalHeader",
            )
        )
        out.append(
            self.get_line(
                "short",
                self._le(rom_bytes[pe_off + 22 : pe_off + 24]),
                "Characteristics",
            )
        )
        out.append("")

        opt_off = pe_off + 24
        opt_end = opt_off + size_opt_hdr
        out.append("/* IMAGE_OPTIONAL_HEADER */")
        out.extend(self._dump_optional_header(rom_bytes, opt_off, opt_end))
        out.append("")

        # Section table — 40 bytes each.
        out.append("/* Section table */")
        sect_off = opt_end
        for i, section in enumerate(pe.sections):
            base = sect_off + i * 40
            out.append(f"/* Section {i}: {section.name!r} */")
            out.append(self.get_line("ascii", rom_bytes[base : base + 8], "Name"))
            out.append(
                self.get_line(
                    "long",
                    self._le(rom_bytes[base + 8 : base + 12]),
                    "VirtualSize",
                )
            )
            out.append(
                self.get_line(
                    "long",
                    self._le(rom_bytes[base + 12 : base + 16]),
                    "VirtualAddress",
                )
            )
            out.append(
                self.get_line(
                    "long",
                    self._le(rom_bytes[base + 16 : base + 20]),
                    "SizeOfRawData",
                )
            )
            out.append(
                self.get_line(
                    "long",
                    self._le(rom_bytes[base + 20 : base + 24]),
                    "PointerToRawData",
                )
            )
            out.append(
                self.get_line(
                    "long",
                    self._le(rom_bytes[base + 24 : base + 28]),
                    "PointerToRelocations",
                )
            )
            out.append(
                self.get_line(
                    "long",
                    self._le(rom_bytes[base + 28 : base + 32]),
                    "PointerToLinenumbers",
                )
            )
            out.append(
                self.get_line(
                    "short",
                    self._le(rom_bytes[base + 32 : base + 34]),
                    "NumberOfRelocations",
                )
            )
            out.append(
                self.get_line(
                    "short",
                    self._le(rom_bytes[base + 34 : base + 36]),
                    "NumberOfLinenumbers",
                )
            )
            out.append(
                self.get_line(
                    "long",
                    self._le(rom_bytes[base + 36 : base + 40]),
                    "Characteristics",
                )
            )
        out.append("")

        # Anything between end-of-section-table and rom_end is alignment padding
        # the linker inserted before the first real section.
        tail_start = sect_off + len(pe.sections) * 40
        if tail_start < self.rom_end:
            out.append("/* Header padding */")
            out.append(
                self._byte_block(rom_bytes[tail_start : self.rom_end], "Padding")
            )

        out.append("")
        return out

    @staticmethod
    def _byte_block(data: bytes, comment: str) -> str:
        if not data:
            return f"/* {comment}: empty */"
        hexed = ", ".join(f"0x{b:02X}" for b in data)
        return f".byte {hexed} /* {comment} */"

    def _summary_block(self, pe) -> List[str]:
        out: List[str] = []
        out.append("/* ============================================================")
        out.append(" * PE / COFF summary (decoded from the bytes below)")
        machine_name = _MACHINE_TYPES.get(pe.machine)
        out.append(
            f" *   Machine:           0x{pe.machine:04X}"
            + (f" ({machine_name})" if machine_name else "")
        )
        base_width = 16 if pe.is_pe32_plus else 8
        out.append(f" *   ImageBase:         0x{pe.image_base:0{base_width}X}")
        if pe.entry_point_rva:
            out.append(
                f" *   EntryPoint:        0x{pe.entry_point_va:0{base_width}X}"
                f"  (RVA 0x{pe.entry_point_rva:X})"
            )
        else:
            out.append(" *   EntryPoint:        (none — DLL with no entry)")
        sub_name = _SUBSYSTEMS.get(pe.subsystem, f"0x{pe.subsystem:04X}")
        out.append(f" *   Subsystem:         {sub_name}")
        if pe.linker_major or pe.linker_minor:
            from ...platforms.win32 import linker_version_label

            out.append(
                f" *   Linker:            {pe.linker_major}.{pe.linker_minor:02d}"
                f"  ({linker_version_label(pe.linker_major, pe.linker_minor)})"
            )
        if pe.coff_num_symbols:
            out.append(
                f" *   COFF symbols:      {pe.coff_num_symbols} at file 0x{pe.coff_symtab_ptr:X}"
                "  (deprecated; unusual for PEs)"
            )
            if pe.coff_symbols:
                shown = pe.coff_symbols[:8]
                out.append(
                    f" *     Sample symbols ({len(shown)} of {len(pe.coff_symbols)}):"
                )
                for sym in shown:
                    out.append(
                        f" *       {sym.name!s:<24s} value=0x{sym.value:08X}"
                        f" section={sym.section_number} class={sym.storage_class}"
                    )
        if pe.clr_header is not None:
            out.append(
                f" *   .NET CLR header:   v{pe.clr_header.runtime_major}."
                f"{pe.clr_header.runtime_minor}"
                f"  flags=0x{pe.clr_header.flags:X}"
            )
            out.append(
                f" *     Metadata:        RVA 0x{pe.clr_header.metadata_rva:X}"
                f"  size 0x{pe.clr_header.metadata_size:X}"
            )
            out.append(
                f" *     EntryPoint token: 0x{pe.clr_header.entry_point_token_or_rva:08X}"
            )
            if pe.clr_header.strong_name_signature_rva:
                out.append(
                    f" *     Strong-name sig: RVA "
                    f"0x{pe.clr_header.strong_name_signature_rva:X}"
                    f"  size 0x{pe.clr_header.strong_name_signature_size:X}"
                )
        if pe.unwind_info:
            out.append(
                f" *   Unwind records:    {len(pe.unwind_info)} decoded "
                f"IMAGE_UNWIND_INFO blobs (PE32+ SEH)"
            )
        if pe.timestamp:
            import datetime as _dt

            try:
                dt = _dt.datetime.fromtimestamp(pe.timestamp, _dt.timezone.utc)
                out.append(
                    f" *   TimeDateStamp:     0x{pe.timestamp:08X}  ({dt.isoformat()})"
                )
            except (OSError, OverflowError, ValueError):
                out.append(f" *   TimeDateStamp:     0x{pe.timestamp:08X}")
        out.append(
            f" *   Characteristics:   {_decode_flags(pe.characteristics, _FILE_CHARACTERISTICS)}"
        )
        if pe.dll_characteristics:
            out.append(
                f" *   DllCharacteristics: {_decode_flags(pe.dll_characteristics, _DLL_CHARACTERISTICS)}"
            )
        out.append(f" *   SectionAlignment:  0x{pe.section_alignment:X}")
        out.append(f" *   FileAlignment:     0x{pe.file_alignment:X}")
        out.append(f" *   SizeOfImage:       0x{pe.size_of_image:X}")
        out.append(f" *   SizeOfHeaders:     0x{pe.size_of_headers:X}")
        if pe.size_of_stack_reserve or pe.size_of_heap_reserve:
            out.append(
                f" *   Stack:             0x{pe.size_of_stack_reserve:X} reserve / 0x{pe.size_of_stack_commit:X} commit"
            )
            out.append(
                f" *   Heap:              0x{pe.size_of_heap_reserve:X} reserve / 0x{pe.size_of_heap_commit:X} commit"
            )
        if pe.pdb_path:
            out.append(f" *   PDB path:          {pe.pdb_path}")
        if pe.pdb_guid:
            age = pe.pdb_age if pe.pdb_age is not None else 0
            out.append(f" *   PDB GUID/Age:      {pe.pdb_guid}-{age}")
        if pe.tls_callback_vas:
            cb_list = ", ".join(f"0x{v:0{base_width}X}" for v in pe.tls_callback_vas)
            out.append(f" *   TLS callbacks:     {cb_list}")
        out.append(" *")
        out.append(" *   Sections:")
        for s in pe.sections:
            flags = []
            if s.is_code:
                flags.append("CODE")
            if s.is_writable:
                flags.append("RW")
            else:
                flags.append("R")
            if s.is_bss:
                flags.append("BSS")
            out.append(
                f" *     {s.name:<10s} VA=0x{(pe.image_base + s.virtual_address):0{base_width}X}"
                f"  VSize=0x{s.virtual_size:X}"
                f"  Raw=0x{s.raw_pointer:X}+0x{s.raw_size:X}"
                f"  [{','.join(flags)}]"
            )
        if pe.exports:
            out.append(" *")
            shown = pe.exports[:8]
            out.append(
                f" *   Exports ({len(pe.exports)} total; showing first {len(shown)}):"
            )
            for exp in shown:
                va = pe.image_base + exp.rva
                if exp.forwarder is not None:
                    out.append(
                        f" *     [{exp.ordinal:>4}] {exp.name or '<unnamed>'} -> {exp.forwarder}"
                    )
                else:
                    out.append(
                        f" *     [{exp.ordinal:>4}] 0x{va:0{base_width}X} {exp.name or '<unnamed>'}"
                    )
        if pe.imports:
            by_dll: dict = {}
            for imp in pe.imports:
                by_dll.setdefault(imp.dll, []).append(imp)
            out.append(" *")
            out.append(
                f" *   Imports ({len(pe.imports)} total from {len(by_dll)} DLLs):"
            )
            for dll, items in by_dll.items():
                out.append(f" *     {dll}: {len(items)}")
        if pe.delay_imports:
            from collections import Counter as _Counter

            by_dll = _Counter(imp.dll for imp in pe.delay_imports)
            out.append(" *")
            out.append(
                f" *   Delay imports ({len(pe.delay_imports)} total from {len(by_dll)} DLLs):"
            )
            for dll, n in by_dll.items():
                out.append(f" *     {dll}: {n}")
        if 0 < len(pe.data_directories) < 16:
            out.append(" *")
            out.append(
                f" *   NumberOfRvaAndSizes: {len(pe.data_directories)}"
                "  (less than the standard 16 — older toolchain or hand-crafted PE)"
            )
        if pe.bound_imports:
            out.append(" *")
            out.append(f" *   Bound imports ({len(pe.bound_imports)}):")
            for bi in pe.bound_imports:
                fwds = (
                    f" + {len(bi.forwarder_refs)} forwarder refs"
                    if bi.forwarder_refs
                    else ""
                )
                out.append(f" *     {bi.dll}  (ts=0x{bi.timestamp:08X}){fwds}")
        if pe.security_cookie_va or pe.safe_seh_handlers or pe.cfg_function_rvas:
            out.append(" *")
            out.append(" *   Load Config:")
            if pe.security_cookie_va:
                out.append(f" *     SecurityCookie:  0x{pe.security_cookie_va:08X}")
            if pe.safe_seh_handlers:
                out.append(f" *     SafeSEH handlers: {len(pe.safe_seh_handlers)}")
            if pe.cfg_function_rvas:
                out.append(
                    f" *     CFG functions:    {len(pe.cfg_function_rvas)} (flags=0x{pe.cfg_flags:X})"
                )
        if pe.runtime_functions:
            out.append(" *")
            out.append(
                f" *   Exception Directory: {len(pe.runtime_functions)} RUNTIME_FUNCTION entries"
            )
        if pe.pointer_rvas:
            out.append(" *")
            out.append(
                f" *   Base relocations: {len(pe.pointer_rvas)} HIGHLOW/DIR64 entries"
            )
        if pe.version_info:
            out.append(" *")
            out.append(" *   VS_VERSIONINFO:")
            # Stable presentation order — most useful fields first.
            preferred = [
                "FileVersion",
                "ProductVersion",
                "ProductName",
                "FileDescription",
                "OriginalFilename",
                "InternalName",
                "CompanyName",
                "LegalCopyright",
            ]
            for key in preferred:
                if key in pe.version_info:
                    out.append(f" *     {key:<18s} {pe.version_info[key]}")
            for key, val in pe.version_info.items():
                if key in preferred:
                    continue
                out.append(f" *     {key:<18s} {val}")
        if pe.resources:
            out.append(" *")
            from collections import Counter
            from ...platforms.win32 import RESOURCE_TYPE_NAMES

            kinds: Counter = Counter()
            for r in pe.resources:
                if isinstance(r.rtype, int):
                    kinds[RESOURCE_TYPE_NAMES.get(r.rtype, f"TYPE_{r.rtype}")] += 1
                else:
                    kinds[str(r.rtype)] += 1
            out.append(f" *   Resources ({len(pe.resources)} total):")
            for kind, n in sorted(kinds.items(), key=lambda kv: -kv[1]):
                out.append(f" *     {kind}: {n}")
        out.append(" * ============================================================ */")
        out.append("")
        return out

    # Named directory slots in the order the PE optional header stores them.
    _DATA_DIRECTORY_NAMES = [
        "Export Table",
        "Import Table",
        "Resource Table",
        "Exception Table",
        "Certificate Table",
        "Base Relocation Table",
        "Debug",
        "Architecture",
        "Global Ptr",
        "TLS Table",
        "Load Config Table",
        "Bound Import",
        "IAT",
        "Delay Import Descriptor",
        "CLR Runtime Header",
        "Reserved",
    ]

    def _dump_optional_header(
        self, rom_bytes: bytes, opt_off: int, opt_end: int
    ) -> List[str]:
        out: List[str] = []
        if opt_end - opt_off < 2:
            out.append(self._byte_block(rom_bytes[opt_off:opt_end], "Optional header"))
            return out

        magic = struct.unpack_from("<H", rom_bytes, opt_off)[0]
        is_pe32_plus = magic == win32_platform.OPT_MAGIC_PE32_PLUS
        size_int = 8 if is_pe32_plus else 4
        size_typ = "quad" if is_pe32_plus else "long"

        # Truncated optional headers — short-circuit if a field would
        # overshoot. Some malformed PEs declare a SizeOfOptionalHeader
        # smaller than the canonical layout; emit whatever fits as raw
        # bytes (once) instead of producing zero-width `.short ""`
        # directives that GAS would reject.
        truncation_emitted = [False]

        def _ensure_room(field_size: int, off: int, label: str) -> bool:
            if off + field_size <= opt_end and off + field_size <= len(rom_bytes):
                return True
            if not truncation_emitted[0]:
                tail = rom_bytes[off : min(opt_end, len(rom_bytes))]
                if tail:
                    out.append(self._byte_block(tail, f"truncated past {label}"))
                truncation_emitted[0] = True
            return False

        def emit_short(off: int, label: str) -> None:
            if not _ensure_room(2, off, label):
                return
            out.append(
                self.get_line("short", self._le(rom_bytes[off : off + 2]), label)
            )

        def emit_long(off: int, label: str) -> None:
            if not _ensure_room(4, off, label):
                return
            out.append(self.get_line("long", self._le(rom_bytes[off : off + 4]), label))

        def emit_int(off: int, label: str) -> None:
            if not _ensure_room(size_int, off, label):
                return
            out.append(
                self.get_line(
                    size_typ, self._le(rom_bytes[off : off + size_int]), label
                )
            )

        o = opt_off
        emit_short(o, "Magic")
        o += 2
        out.append(self.get_line("byte", rom_bytes[o : o + 1], "MajorLinkerVersion"))
        o += 1
        out.append(self.get_line("byte", rom_bytes[o : o + 1], "MinorLinkerVersion"))
        o += 1
        emit_long(o, "SizeOfCode")
        o += 4
        emit_long(o, "SizeOfInitializedData")
        o += 4
        emit_long(o, "SizeOfUninitializedData")
        o += 4
        emit_long(o, "AddressOfEntryPoint")
        o += 4
        emit_long(o, "BaseOfCode")
        o += 4
        if not is_pe32_plus:
            emit_long(o, "BaseOfData")
            o += 4

        emit_int(o, "ImageBase")
        o += size_int
        emit_long(o, "SectionAlignment")
        o += 4
        emit_long(o, "FileAlignment")
        o += 4
        emit_short(o, "MajorOperatingSystemVersion")
        o += 2
        emit_short(o, "MinorOperatingSystemVersion")
        o += 2
        emit_short(o, "MajorImageVersion")
        o += 2
        emit_short(o, "MinorImageVersion")
        o += 2
        emit_short(o, "MajorSubsystemVersion")
        o += 2
        emit_short(o, "MinorSubsystemVersion")
        o += 2
        emit_long(o, "Win32VersionValue")
        o += 4
        emit_long(o, "SizeOfImage")
        o += 4
        emit_long(o, "SizeOfHeaders")
        o += 4
        emit_long(o, "CheckSum")
        o += 4
        emit_short(o, "Subsystem")
        o += 2
        emit_short(o, "DllCharacteristics")
        o += 2
        emit_int(o, "SizeOfStackReserve")
        o += size_int
        emit_int(o, "SizeOfStackCommit")
        o += size_int
        emit_int(o, "SizeOfHeapReserve")
        o += size_int
        emit_int(o, "SizeOfHeapCommit")
        o += size_int
        emit_long(o, "LoaderFlags")
        o += 4
        num_dirs_off = o
        num_dirs = struct.unpack_from("<I", rom_bytes, num_dirs_off)[0]
        emit_long(o, "NumberOfRvaAndSizes")
        o += 4

        # Data directories — each is {VirtualAddress, Size}. PE spec caps
        # the canonical count at 16; honour but tolerate a slightly
        # higher declared count (loaders accept up to whatever fits in
        # the optional header). Cap iteration at 256 to bound malformed
        # inputs that claim millions of directory entries.
        if num_dirs > 0:
            out.append("/* Data directories */")
        for i in range(min(num_dirs, 256)):
            if o + 8 > opt_end:
                break
            label = (
                self._DATA_DIRECTORY_NAMES[i]
                if i < len(self._DATA_DIRECTORY_NAMES)
                else f"Directory {i}"
            )
            emit_long(o, f"{label}.VirtualAddress")
            emit_long(o + 4, f"{label}.Size")
            o += 8

        # Anything left inside the declared optional header (trailing reserved
        # bytes) gets dumped raw so we round-trip cleanly.
        if o < opt_end:
            out.append(self._byte_block(rom_bytes[o:opt_end], "Optional header tail"))

        return out
