name: black

on:
  push:
  pull_request:

jobs:
  black_checks:
    runs-on: ubuntu-latest
    name: black
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install black
        pip install -r requirements.txt
        pip install types-PyYAML
    - name: black
      run: black --check .
