# Taken from https://nimblehq.co/blog/create-github-wiki-pull-request

name: Publish docs to Wiki

# Trigger this action only if there are changes pushed to the docs/** directory under the main branch
on:
  push:
    paths:
      - docs/** # This includes all sub folders
    branches:
      - main # This can be changed to any branch of your preference

env:
  USER_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }} # This is the repository secret
  OWNER: ${{ github.event.repository.owner.name }} # This is the repository owner
  REPOSITORY_NAME: ${{ github.event.repository.name }} # This is the repository name

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      # 1. Create folder named `tmp_wiki`
      # 2. Initialize Git
      # 3. Pull old Wiki content
      # `git log -1 --pretty=%aN` prints the current commit's author name
      # `git log -1 --pretty=%aE` prints the current commit's author mail
      - name: Pull content from wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git config user.name $(git log -1 --pretty=%aN)
          git config user.email $(git log -1 --pretty=%aE)
          git pull https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git
      # 4. Synchronize differences between `docs` & `tmp_wiki`
      # 5. Push new Wiki content
      # `git log -1 --pretty=%B` prints the current commit's message
      - name: Push content to wiki
        run: |
          rsync -av --delete docs/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git add .
          git commit -m "$(git log -1 --pretty=%B)"
          git push -f --set-upstream https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git master
